# Generated by Django 3.0.5 on 2020-05-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions180', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
